luv-test/luv-dmesg-acpi-tables-dump: Avoid creating directory structures
luv-dmesg-acpi-tables-dump creates a mount point, mounts luv results
partition there and then dumps dmesg, cpuinfo, acpitables. This
is a convoluted method. Instead, we could pass LUV_SAVE_RESULTS_DIR as
an argument, create a directory named "dumps" and directly dump dmesg,
cpuinfo and acpitables.

Tested-By: Naresh Bhat <naresh.bhat@linaro.org>
Reviewed-by: Naresh Bhat <naresh.bhat@linaro.org>
Reviewed-by: Ricardo Neri <ricardo.neri-calderon@linux.intel.com>
Reported-by: Ricardo Neri <ricardo.neri-calderon@linux.intel.com>
Signed-off-by: Sai Praneeth Prakhya <sai.praneeth.prakhya@intel.com>
Signed-off-by: Megha Dey <megha.dey@linux.intel.com>

diff --git a/meta-luv/recipes-core/luv-test/luv-test/luv-dmesg-acpi-tables-dump b/meta-luv/recipes-core/luv-test/luv-test/luv-dmesg-acpi-tables-dump
--- a/meta-luv/recipes-core/luv-test/luv-test/luv-dmesg-acpi-tables-dump
+++ b/meta-luv/recipes-core/luv-test/luv-test/luv-dmesg-acpi-tables-dump
@@ -11,26 +11,18 @@
 #
 #####################################################################
 
-# Definitions for disk partitions and mount points
-DUMP=/mnt/dump/
-LUV_STORAGE_UUID=05D6-1523
+# Definition for luv results folder
 LUV_SAVE_RESULTS_DIR=$1
 
-# Create a temporary mount point and run "fwts -d" command to dump dmesg,
-# cpuinfo and ACPI tables
+# Create a directory named "dumps" in luv results folder and run
+# "fwts -d" command to dump dmesg, cpuinfo and ACPI tables
 gen_dmesg_acpi_dumps() {
-    # Definitions for disk partitions and mount points
-    mkdir -p ${DUMP}
-    if [ $? -eq 0 ]; then
-        mount /dev/disk/by-uuid/${LUV_STORAGE_UUID} ${DUMP}
-        if [ $? -eq 0 ]; then
-			mkdir -p ${DUMP}${LUV_SAVE_RESULTS_DIR}/dumps
-            if [ $? -eq 0 ] ; then
-				cd ${DUMP}${LUV_SAVE_RESULTS_DIR}/dumps
-				fwts -d
-				umount ${DUMP}
-            fi
-        fi
+    mkdir -p ${LUV_SAVE_RESULTS_DIR}/dumps
+    if [ $? -eq 0 ] ; then
+        cd ${LUV_SAVE_RESULTS_DIR}/dumps
+        fwts -d
+    else
+        echo "Failed to create dumps directory"
     fi
 }
 
