luv-dmesg-acpi-tables-dump: Fix the indentation in list_dsms()
list_dsms() has an indentation, where tabs are used while the
gen_dmesg_acpi_dumps() followed spaces. It is recommended to follow
one indentation through the entire script. Thus fix the indentation
for list_dsms().

Cc: Ricardo Neri <ricardo.neri@intel.com>
Cc: Naresh Bhat <naresh.bhat@linaro.org>
Cc: Sai Prakhya <sai.praneeth.prakhya@intel.com>
Signed-off-by: Gayatri Kammela <gayatri.kammela@intel.com>
Signed-off-by: Megha Dey <megha.dey@linux.intel.com>

diff --git a/meta-luv/recipes-core/luv-test/luv-test/luv-dmesg-acpi-tables-dump b/meta-luv/recipes-core/luv-test/luv-test/luv-dmesg-acpi-tables-dump
--- a/meta-luv/recipes-core/luv-test/luv-test/luv-dmesg-acpi-tables-dump
+++ b/meta-luv/recipes-core/luv-test/luv-test/luv-dmesg-acpi-tables-dump
@@ -37,46 +37,46 @@ gen_dmesg_acpi_dumps() {
 # iasl -d <file> :	Disassemble binary ACPI tables (*.dat to *.dsl)
 # iasl -so <file>:	Create namespace AML offset table in C (*.offset.h)
 list_dsms() {
-	cd ${LUV_SAVE_RESULTS_DIR}/dumps
-	if [ $? -eq 0 ] ; then
-		mkdir -p temp
-		if [ $? -eq 0 ] ; then
-			cd temp
-			acpixtract -a ../acpidump.log &> /dev/null
-			dsdt_dat_file=`ls | grep "dsdt.dat"`
-			if [ -z "${dsdt_dat_file}" ] ; then
-				echo "Unable to find DSDT.dat file, aborting listing dsm's!"
-				return 1
-			fi
-			ssdt_dat_files=`ls | grep "ssdt*"`
-			if [ -z "${ssdt_dat_files}" ] ; then
-				echo "Didn't find any SSDT .dat files"
-			else
-				iasl -d ${ssdt_dat_files} &> /dev/null
-				ssdt_dsl_files=`ls | grep ".dsl"`
-				iasl -so ${ssdt_dsl_files} &> /dev/null
-			fi
-			iasl -d dsdt.dat &> /dev/null
-			iasl -so dsdt.dsl &> /dev/null
-			off_h_files=`ls | grep "offset.h"`
-			if [ -z "${off_h_files}" ] ; then
-				echo "Unable to find any offset.h files, aborting listing dsm's!"
-				return 1
-			fi
-			grep -H -e "_DSM" $off_h_files | grep -e "METHOD" | \
-				awk -F':' -F'"' '{print$1$2}' | tr -d { > ../list_of_dsms
-			cd ..
-			rm -rf temp
-			num_of_dsms=`wc -w < list_of_dsms`
-			if [ ${num_of_dsms} -eq 0 ] ; then
-				echo "No _DSM's found" > list_of_dsms
-			fi
-		else
-			echo "Failed to create directory to extract ACPI tables"
-		fi
-	else
-		echo "Failed to find dumps directory"
-	fi
+    cd ${LUV_SAVE_RESULTS_DIR}/dumps
+    if [ $? -eq 0 ] ; then
+        mkdir -p temp
+        if [ $? -eq 0 ] ; then
+            cd temp
+            acpixtract -a ../acpidump.log &> /dev/null
+            dsdt_dat_file=`ls | grep "dsdt.dat"`
+            if [ -z "${dsdt_dat_file}" ] ; then
+                echo "Unable to find DSDT.dat file, aborting listing dsm's!"
+                return 1
+            fi
+            ssdt_dat_files=`ls | grep "ssdt*"`
+            if [ -z "${ssdt_dat_files}" ] ; then
+                echo "Didn't find any SSDT .dat files"
+            else
+                iasl -d ${ssdt_dat_files} &> /dev/null
+                ssdt_dsl_files=`ls | grep ".dsl"`
+                iasl -so ${ssdt_dsl_files} &> /dev/null
+            fi
+            iasl -d dsdt.dat &> /dev/null
+            iasl -so dsdt.dsl &> /dev/null
+            off_h_files=`ls | grep "offset.h"`
+            if [ -z "${off_h_files}" ] ; then
+                echo "Unable to find any offset.h files, aborting listing dsm's!"
+                return 1
+            fi
+            grep -H -e "_DSM" $off_h_files | grep -e "METHOD" | \
+            awk -F':' -F'"' '{print$1$2}' | tr -d { > ../list_of_dsms
+            cd ..
+            rm -rf temp
+            num_of_dsms=`wc -w < list_of_dsms`
+            if [ ${num_of_dsms} -eq 0 ] ; then
+                echo "No _DSM's found" > list_of_dsms
+            fi
+        else
+            echo "Failed to create directory to extract ACPI tables"
+        fi
+    else
+        echo "Failed to find dumps directory"
+    fi
 }
 
 gen_dmesg_acpi_dumps
