luv-test-manager: Save results to non-volatile media
Add functionality to save the test results to non-volatile media.  The
non-volatile media is expected to be a disk identified by its UUID. The
disk is mounted using the UUID to avoid writing inadvertently writing to
any other disk present in the system.

Clearly, this implementation requires the presence of a disk with the
UUID specified by the script. Thus, it is required to utilize such UUID
when creating the filesystem.

Also, disks in some systems take a while to be ready for mount and may
not be ready when the LUV test manager runs. Thus, a delay of 5 seconds
is introduced in order to increase the likelihood of finding the
intended disk.

Signed-off-by: Ricardo Neri <ricardo.neri-calderon@linux.intel.com>
Signed-off-by: Matt Fleming <matt.fleming@intel.com>

diff --git a/meta-luv/recipes-core/initscripts/initscripts/luv-test-manager b/meta-luv/recipes-core/initscripts/initscripts/luv-test-manager
--- a/meta-luv/recipes-core/initscripts/initscripts/luv-test-manager
+++ b/meta-luv/recipes-core/initscripts/initscripts/luv-test-manager
@@ -14,6 +14,41 @@ psplash_write() {
     fi
 }
 
+# Save test results to a disk. In order to reliable identify the
+# correct partition, mount using the disk's UUID. If the partition
+# cannot be mounted, test results are not saved.
+
+LUV_SAVE_RAW_DIR=/dev/null
+LUV_SAVE_PARSED_DIR=/dev/null
+LUV_SAVE_RESULTS_DIR=/dev/null
+
+LUV_STORAGE=/mnt/luv-storage/
+LUV_PARTITION_UUID=05D6-1523
+LUV_DISK_DEVICE=/dev/disk/by-uuid/${LUV_PARTITION_UUID}
+
+mkdir -p ${LUV_STORAGE}
+if [ $? -eq 0 ]; then
+    # Not all disks may be ready to mount at this moment.
+    # Thus, we need to wait for them.
+    psplash_write "MSG Preparing test setup..."
+    for n in 0 25 50 75 100
+    do
+        psplash_write "PROGRESS $n"
+        sleep 1
+    done
+
+    mount ${LUV_DISK_DEVICE} ${LUV_STORAGE}
+    if [ $? -eq 0 ]; then
+        LUV_SAVE_RESULTS_DIR=${LUV_STORAGE}luv-results/
+
+        mkdir -p ${LUV_SAVE_RESULTS_DIR}raw/
+        [ $? -eq 0 ] && LUV_SAVE_RAW_DIR=${LUV_SAVE_RESULTS_DIR}raw/
+
+        mkdir -p ${LUV_SAVE_RESULTS_DIR}parsed/
+        [ $? -eq 0 ] && LUV_SAVE_PARSED_DIR=${LUV_SAVE_RESULTS_DIR}parsed
+    fi
+fi
+
 psplash_write "MSG Running tests..."
 
 cat <<EOF
@@ -59,21 +94,31 @@ for r in $runner_list; do
         parser="/bin/cat"
     }
 
-    $runner | tee ${LUV_LOG_DIR}/$r | $parser | ${LUV_PARSER_DIR}/test-manager
+    $runner | tee ${LUV_LOG_DIR}/$r | tee ${LUV_SAVE_RAW_DIR}/$r | $parser | \
+              tee ${LUV_SAVE_PARSED_DIR}/$r | ${LUV_PARSER_DIR}/test-manager
+    sync
 done | awk '/      \[\+/ { units += 1 }
     /    \[\-/ { suites += 1 }
     /pass/ { passes += 1 }
     /fail/ { fails += $3 }
     /skip/ { skips += 1 }
     END {
-	printf("\nRan %d testsuites and %d unittests, %d passes, %d fails, %d skipped\n", suites, units, passes, fails, skips)
+	printf("\nRan %d testsuites and %d unittests, %d passes, %d fails, %d skipped.\n", suites, units, passes, fails, skips)
     }
 
-    { print $0 }' | tee /tmp/luv.results
+    { print $0 }' | tee /tmp/luv.results | tee ${LUV_SAVE_RESULTS_DIR}/luv.results
+
+mountpoint -q ${LUV_STORAGE}
+if [ $? -eq 0 ]; then
+    umount ${LUV_STORAGE}
+    SAVE_STATUS="You may remove the storage media."
+else
+    SAVE_STATUS="Results were not saved in storage media."
+fi
 
 [ -e $FIFO ] && {
     echo "DONE" > $FIFO
-    grep "Ran" /tmp/luv.results | awk '{printf "MSG %s\n", $0}' > $FIFO
+    grep "Ran" /tmp/luv.results | awk '{printf "MSG %s\n%s\n", $0, "'"$SAVE_STATUS"'"}' > $FIFO
 
     umount -l /mnt/.psplash
 }
